version: '3.4'
services:
  launchcode_challenge:
    depends_on:
      - postgres
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn start:migrate:prod
    ports:
      - 80:3000
    networks:
      - api

  postgres:
    image: postgres
    networks:
      - api
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - launchcode_challenge:/var/lib/postgresql/data

networks:
  api:

volumes:
  launchcode_challenge:
